backend:
  name: github
  repo: bluerosegarden/dandy-site
  branch: main

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
- name: "portfolio" # Used in routes, e.g., /admin/collections/blog
  label: "Portfolio" # Used in the UI
  folder: "portfolio" # The path to the folder where the documents are stored
  format: json
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Image", name: "thumbnail", widget: "image"}
    - {label: "Description", name: "desc", widget: "string"}
    - {label: "Link", name: "link", widget: "string"}